[package]
name = "rust-lienzo-webgl-engine"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.14.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.128"
wasm-bindgen = "0.2.93"

[lib]
crate-type = ["cdylib"]